Update CI workflow directory

diff --git a/.github/workflows/python-app.yml b/.github/workflows/python-app.yml
--- a/.github/workflows/python-app.yml
+++ b/.github/workflows/python-app.yml
@@ -1,7 +1,3 @@
-# This workflow will install Python dependencies, run tests and lint with a single version of Python
-# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python
-
-
 name: CI Pipeline
 
 on:
@@ -19,33 +15,39 @@ jobs:
     strategy:
       matrix:
         service: [machine-learning-client, web-app]
-    
+
     steps:
+    - name: Checkout code
+      uses: actions/checkout@v4
+
+    - name: Debug directory structure
+      run: ls -R
 
     - name: Set up Python
       uses: actions/setup-python@v4
       with:
         python-version: '3.12'
 
-    - name: Install pipenv
-      run: pip install pipenv
-
     - name: Install dependencies
-      working-directory: ./${{ matrix.service }}
+      working-directory: ${{ matrix.service }}
       run: |
+        python -m pip install --upgrade pip
+        python -m pip install pipenv
         pipenv install --dev
+
     - name: Run linting
-      working-directory: ./${{ matrix.service }}
+      working-directory: ${{ matrix.service }}
       run: |
         if [ "${{ matrix.service }}" == "machine-learning-client" ]; then
-          pipenv run pylint src/main.py
+          [ -f src/main.py ] && pipenv run pylint src/main.py || echo "src/main.py not found"
         elif [ "${{ matrix.service }}" == "web-app" ]; then
-          pipenv run pylint app.py
+          [ -f app.py ] && pipenv run pylint app.py || echo "app.py not found"
         fi
+
     - name: Format code with Black
-      working-directory: ./${{ matrix.service }}
+      working-directory: ${{ matrix.service }}
       run: pipenv run black --check .
+
     - name: Run tests
-      working-directory: ./${{ matrix.service }}
-      run: |
-        pipenv run pytest
+      working-directory: ${{ matrix.service }}
+      run: pipenv run pytest
